# Generated by Django 5.0.4 on 2024-05-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_operator',
            field=models.BooleanField(default=False, help_text='Adds operator permissions to user',
                                      verbose_name='Operator'),
        ),
    ]
