# Generated by Django 5.0.6 on 2024-05-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_is_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_operator',
            field=models.BooleanField(default=False, help_text='<p id="is-op-help-text">Adiciona permissões de '
                                                               'operador ao usuário</p>', verbose_name='Operator'),
        ),
    ]
