services:
  database:
    container_name: work_at_codev_db
    image: postgres
    restart: no
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5437:5432

  rbmq:
    image: rabbitmq
    restart: no
    env_file: .env
    ports:
      - 5672:5672
