services:
  database:
    container_name: work_at_codev_db
    image: postgres
    restart: no
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_USER: dbuser
      POSTGRES_DB: codevance_db
    ports:
      - 5437:5432

  rbmq:
    image: rabbitmq
    restart: no
    environment:
      RABBITMQ_NODENAME: my-rabbit
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbitpass
    ports:
      - 5672:5672
