# fly.toml app configuration file generated for work-at-codevance on 2024-05-23T10:57:40-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'work-at-codevance'
primary_region = 'gru'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = './start.sh'

[env]
  PORT = '8000'

[processes]
  app = 'gunicorn --bind :8000 --workers 2 workatcodev.wsgi'
  worker = 'python -m celery -A workatcodev worker -l info'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '768mb'

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
