# Generated by Django 5.0.4 on 2024-04-17 19:05

import django.db.models.deletion
import workatcodev.base.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                  parent_link=True, primary_key=True, serialize=False,
                                                  to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('base.user',),
            managers=[
                ('objects', workatcodev.base.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('user_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('corporate_name', models.CharField(max_length=64, verbose_name='Razão social')),
                ('cnpj', models.CharField(help_text='Use apenas números', max_length=14, verbose_name='CNPJ')),
            ],
            options={
                'abstract': False,
            },
            bases=('base.user',),
            managers=[
                ('objects', workatcodev.base.models.UserManager()),
            ],
        ),
    ]
