# Generated by Django 5.0.4 on 2024-04-26 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('due_date', models.DateField(verbose_name='Vencimento')),
                ('value', models.PositiveIntegerField(verbose_name='Valor original')),
                ('status', models.CharField(
                    choices=[('U', 'Unavailable'), ('A', 'Available'), ('PC', 'Pending confirmation'),
                             ('AN', 'Anticipated'), ('D', 'Denied')], default='A', editable=False,
                    verbose_name='Status')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.supplier',
                                               verbose_name='Fornecedor')),
            ],
        ),
    ]
