# Generated by Django 5.0.4 on 2024-04-26 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Valor'),
        ),
        migrations.CreateModel(
            name='Anticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Data da solicitação')),
                ('new_due_date', models.DateField(verbose_name='Novo vencimento')),
                ('new_value', models.PositiveIntegerField(editable=False, verbose_name='Valor com desconto')),
                ('update', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('status',
                 models.CharField(choices=[('A', 'Approved'), ('PC', 'Pending confirmation'), ('D', 'Denied')],
                                  default='PC', editable=False, verbose_name='Status')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payment',
                                              verbose_name='Pagamento')),
            ],
        ),
    ]
