# Generated by Django 5.0.4 on 2024-05-06 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_status_alter_anticipation_new_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticipation',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.payment',
                                       verbose_name='Pagamento'),
        ),
    ]
