# Generated by Django 5.0.4 on 2024-05-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_anticipation_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticipation',
            name='new_value',
            field=models.FloatField(verbose_name='Valor com desconto'),
        ),
    ]
