# Generated by Django 5.0.6 on 2024-05-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_requestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(help_text='<p id="cnpj-help-text">Only numbers</p>', max_length=14, unique=True,
                                   verbose_name='CNPJ'),
        ),
    ]
