# Generated by Django 5.0.6 on 2024-05-16 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_supplier_cnpj'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(help_text='<p id="cnpj-help-text">Apenas números</p>', max_length=14,
                                   unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='corporate_name',
            field=models.CharField(max_length=128, verbose_name='Corporate name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                       verbose_name='User'),
        ),
    ]
