# Generated by Django 5.0.6 on 2024-05-16 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0009_alter_supplier_cnpj_alter_supplier_corporate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticipation',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Request date'),
        ),
        migrations.AlterField(
            model_name='anticipation',
            name='new_due_date',
            field=models.DateField(verbose_name='New due date'),
        ),
        migrations.AlterField(
            model_name='anticipation',
            name='new_value',
            field=models.FloatField(verbose_name='Discounted value'),
        ),
        migrations.AlterField(
            model_name='anticipation',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.payment',
                                       verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='anticipation',
            name='update',
            field=models.DateField(auto_now=True, verbose_name='Updated in'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Inserted in'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='due_date',
            field=models.DateField(verbose_name='Due date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.supplier',
                                    verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=models.FloatField(verbose_name='Value'),
        ),
    ]
