name: workflow

on: push

jobs:
  CI:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: passworkflow
          POSTGRES_USER: userworkflow
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: x64

      - name: Instalar pipenv
        run: pip install pipenv

      - name: Instalar dependências
        run: pipenv sync --dev

      - name: Checar vulnerabilidades
        run: pipenv check

      - name: Rodar flake8
        run: pipenv run flake8

      - name: Criar mensagens (traduções)
        run: python manage.py makemessages

      - name: Compilar mensagens (traduções)
        run: python manage.py compilemessages

      - name: Setup env
        run: cp contrib/env-sample .env

      - name: Rodar testes automáticos
        run: pipenv run pytest --cov=workatcodev

      - name: Upload coverage reports to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: pipenv run codecov
