name: workflow

on: push

jobs:
  CI:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: passworkflow
          POSTGRES_USER: userworkflow
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: x64

      - name: Install pipenv
        run: pip install pipenv

      - name: Install libraries
        run: pipenv sync --dev

      - name: Check vulnerabilities
        run: pipenv check

      - name: Run flake8
        run: pipenv run flake8

      - name: Setup env
        run: cp contrib/env-sample .env

      - name: Run tests
        run: pipenv run pytest --cov=workatcodev

      - name: Upload coverage reports to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: pipenv run codecov

  deploy:
      needs: CI
      if: github.ref == 'refs/heads/main'  # runs deploy only if the push action is on branch main
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}